### ISSUE TITLE
是否同一个session同时被执行和释放操作获取到了(The session was released, couldn't use again)

### ISSUE THREAD

**Issue by soul-gin** [nebula-contrib/ngbatis#129]
[{"age":9,"name":"Lily"},{"age":13,"name":"Jerry"},{"age":10,"name":"Tom"},{"age":11,"name":"John"}]
2023-02-02 17:34:42.054  INFO 3192 --- [pool-2-thread-1] o.n.c.n.s.IntervalCheckSessionDispatcher : LocalSession in queue which created at 1675330450783, useCount: 634
[{"age":9,"name":"Lily"},{"age":13,"name":"Jerry"},{"age":10,"name":"Tom"},{"age":11,"name":"John"}]
2023-02-02 17:34:42.103  INFO 3192 --- [pool-2-thread-1] o.n.c.n.s.IntervalCheckSessionDispatcher : Release a session which created at 1675330450783
2023-02-02 17:34:42.103  INFO 3192 --- [           main] o.n.c.n.s.IntervalCheckSessionDispatcher : Release a session which created at 1675330450783
org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败：The session was released, couldn't use again.
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeWithParameter(MapperProxy.java:233)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:126)
	at org.nebula.contrib.ngbatis.proxy.NebulaDaoBasic.selectByIds(NebulaDaoBasic.java:65)
	at ye.weicheng.ngbatis.demo.NebulaBasicDaoTests.upsertByIdSelectiveLoop3(NebulaBasicDaoTests.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: com.vesoft.nebula.client.graph.exception.IOErrorException: The session was released, couldn't use again.
	at com.vesoft.nebula.client.graph.net.Session.executeWithParameter(Session.java:99)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeWithParameter(MapperProxy.java:225)
	... 70 more
[{"age":9,"name":"Lily"},{"age":13,"name":"Jerry"},{"age":10,"name":"Tom"},{"age":11,"name":"John"}]

**Comment by soul-gin** [comment]
场景: 调整下面两个参数后, 循环执行一条查询语句
public static long SESSION_LIFE_LENGTH = 2000;
public static long CHECK_FIXED_RATE = 2000; // unit ms

**Comment by CorvusYe** [comment]
这个问题我有疑问的是：
- run 当中 release 的应该是 sessionQueue 当中的元素
- 但 poll 取出使用时，当前元素已经不在 sessionQueue 内了，按理不应该被释放才对

> 这块是否把run方法抽取出来, 用 synchronized 修饰下, 以对应
> public synchronized LocalSession poll() {}

如果是已经取出了的元素还能通过 sessionQueue 被释放掉，那可能需要加锁的不仅仅是 run 方法，可能更应该是 release 跟 poll 需要同一个对象锁。保证取时不释放，释放时不取。

不懂我上面的理解对不对，是不是有不太对的细节导致了这个问题。

**Comment by CorvusYe** [comment]
我应该是找到原因了：
```java
  @Override
  public void release(LocalSession session) {
    session.getSession().release();
    log.info("Release a session which created at {}", session.getBirth());
    sessionQueue.remove(session);
  }
```
```java
  @Override
  public synchronized LocalSession poll() {
      ...
      localSession = sessionQueue.poll(nebulaPoolConfig.getWaitTime(), TimeUnit.MILLISECONDS);
      ...
  }
```

在多线程的场景下，执行顺序是这样的：

```java
    // 两条线程
    // 一条进了 release 方法（此时拿到的session入参还在队内）
    // 另一条进了 poll 方法（把即将 release 的 session 拿走，出队）
      localSession = sessionQueue.poll(nebulaPoolConfig.getWaitTime(), TimeUnit.MILLISECONDS); // poll
    session.getSession().release(); // release
      // executeWithParameter
    log.info("Release a session which created at {}", session.getBirth()); // release
    sessionQueue.remove(session); // release 这个时候的 session 即第一句的 localSession 已经不在队内，结果 false
```

可以帮忙确认下日志里报错的时候，sessionQueue.remove 的结果值是不是 false。
报错的是 执行了 poll 的线程，应该不影响执行了 release 的线程往下执行，这个值应该拿得到。

**Comment by CorvusYe** [comment]
我应该是找到原因了：
```java
  @Override
  public void release(LocalSession session) {
    session.getSession().release();
    log.info("Release a session which created at {}", session.getBirth());
    sessionQueue.remove(session);
  }
```
```java
  @Override
  public synchronized LocalSession poll() {
      ...
      localSession = sessionQueue.poll(nebulaPoolConfig.getWaitTime(), TimeUnit.MILLISECONDS);
      ...
  }
```

在多线程的场景下，执行顺序是这样的：

```java
    // 两条线程
    // 一条进了 release 方法（此时拿到的session入参还在队内）
    // 另一条进了 poll 方法（把即将 release 的 session 拿走，出队）
      localSession = sessionQueue.poll(nebulaPoolConfig.getWaitTime(), TimeUnit.MILLISECONDS); // poll
    session.getSession().release(); // release
      // executeWithParameter
    log.info("Release a session which created at {}", session.getBirth()); // release
    sessionQueue.remove(session); // release 这个时候的 session 即第一句的 localSession 已经不在队内，结果 false
```

可以帮忙确认下日志里报错的时候，sessionQueue.remove 的结果值是不是 false。
报错的是 执行了 poll 的线程，应该不影响执行了 release 的线程往下执行，这个值应该拿得到。

**Comment by soul-gin** [comment]
是的, sessionQueue.remove 的结果值是 false.
sessionQueue的迭代器看起来是返回的一个新对象,迭代的应该是瞬时快照.
另外,如果session总是被poll方法抢到,可能会让应该释放的session没有得到释放;暂时想到是可以在handleSession时判断一下.

```
2023-02-03 11:31:10.345  INFO 12908 --- [pool-2-thread-1] o.n.c.n.s.IntervalCheckSessionDispatcher : LocalSession in queue which created at 1675395070065, useCount: 1
2023-02-03 11:31:49.351  INFO 12908 --- [pool-2-thread-1] o.n.c.n.s.IntervalCheckSessionDispatcher : LocalSession in queue which created at 1675395070065, useCount: 858
2023-02-03 11:31:49.397  INFO 12908 --- [pool-2-thread-1] o.n.c.n.s.IntervalCheckSessionDispatcher : Release a session which created at 1675395070065
2023-02-03 11:31:49.397  INFO 12908 --- [pool-2-thread-1] o.n.c.n.s.IntervalCheckSessionDispatcher : Release a session which created at 1675395070065 removeFlag=false
2023-02-03 11:31:49.397  INFO 12908 --- [           main] o.n.c.n.s.IntervalCheckSessionDispatcher : Release a session which created at 1675395070065
2023-02-03 11:31:49.397  INFO 12908 --- [           main] o.n.c.n.s.IntervalCheckSessionDispatcher : Release a session which created at 1675395070065 removeFlag=false
org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败：The session was released, couldn't use again.
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeWithParameter(MapperProxy.java:233)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:126)
	at org.nebula.contrib.ngbatis.proxy.NebulaDaoBasic.selectByIds(NebulaDaoBasic.java:65)
```
