### ISSUE TITLE
依赖jar冲突

### ISSUE THREAD

**Issue by saviour11** [nebula-contrib/ngbatis#191]
集成项目禁用 com.alibaba.fastjson; 引入ngbatis后，去除改依赖，就没法正常使用了；
2、 beelt-core疑似也冲突
严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.beetl.core.GroupTemplate.getTemplate(Ljava/lang/String;)Lorg/beetl/core/Template;] with root cause
java.lang.NoSuchMethodError: org.beetl.core.GroupTemplate.getTemplate(Ljava/lang/String;)Lorg/beetl/core/Template;
	at org.nebula.contrib.ngbatis.binding.BeetlTextRender.resolve(BeetlTextRender.java:34)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:125)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:169)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.pageSupport(MapperProxy.java:185)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:89)
	at com.demo.dao.mapper.nebula.NebulaMapper$Proxy.selectNode(Unknown Source)

**Comment by CorvusYe** [comment]
fastjson: 1.2.83
beetl: 3.1.8.RELEASE
ngbatis用的是这两个版本。

可以提供下项目中 beetl 的版本吗

fastjson是早期引入的依赖，印象中现在的ngbatis可以不需要，
我看看能不能也从源码中移除掉

**Comment by saviour11** [comment]
项目中用的是beetl&nbsp;3.14.1.RELEASE 
从错误描述来看，可能是jar包冲突引起的。 我这边再看一下 如何解决


Saviour
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nebula-contrib/ngbatis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 中午12:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nebula-contrib/ngbatis] 依赖jar冲突 (Issue #191)





 
fastjson: 1.2.83
 beetl: 3.1.8.RELEASE
 ngbatis用的是这两个版本。
 
可以提供下项目中 beetl 的版本吗
 
fastjson是早期引入的依赖，印象中现在的ngbatis可以不需要，
 我看看能不能也从源码中移除掉
