### ISSUE TITLE
PersonDao Mappper Proxy

### ISSUE THREAD

**Issue by AhYi8** [nebula-contrib/ngbatis#233]
# 新项目启动报这个异常：
```java
java.lang.NullPointerException: null
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:73) ~[ngbatis-1.1.3.jar:1.1.3]
	at com.ayi.ngbatis.dao.PersonDao$Proxy.select1(Unknown Source) ~[na:na]
	at com.ayi.ngbatis.service.impl.PersonServiceImpl.select1(PersonServiceImpl.java:79) ~[classes/:na]
	at com.ayi.ngbatis.controller.PersonController.select1(PersonController.java:18) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_321]
	......
```
# 启动类
![图片](https://github.com/nebula-contrib/ngbatis/assets/56581248/e15c3378-90db-4097-97eb-8e06e3c9f081)
# 项目结构
![图片](https://github.com/nebula-contrib/ngbatis/assets/56581248/e34c0cec-d525-4326-85d0-6e917b590e91)
# Dao 类
![图片](https://github.com/nebula-contrib/ngbatis/assets/56581248/1aee4661-028c-41cc-ae4e-8812abebfb0c)
# ServiceImp 类
![图片](https://github.com/nebula-contrib/ngbatis/assets/56581248/cde9b5fc-937a-4ce5-8764-7c559b2abd16)

**Comment by AhYi8** [comment]
哪位大佬知道为啥，刚学，踩的坑太多了

**Comment by AhYi8** [comment]
这是Mapper.xml 文件
![图片](https://github.com/nebula-contrib/ngbatis/assets/56581248/493095cf-8538-4f69-90aa-c594ec05acf3)

**Comment by CorvusYe** [comment]
> # 新项目启动报这个异常：
> ```java
> java.lang.NullPointerException: null
> 	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:73) ~[ngbatis-1.1.3.jar:1.1.3]
> 	at com.ayi.ngbatis.dao.PersonDao$Proxy.select1(Unknown Source) ~[na:na]
> 	at com.ayi.ngbatis.service.impl.PersonServiceImpl.select1(PersonServiceImpl.java:79) ~[classes/:na]
> 	at com.ayi.ngbatis.controller.PersonController.select1(PersonController.java:18) ~[classes/:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_321]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_321]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_321]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_321]
> 	......
> ```
> 
> # 启动类
> ![图片](https://user-images.githubusercontent.com/56581248/270079241-e15c3378-90db-4097-97eb-8e06e3c9f081.png)

这里的报空是因为基本包的内置组件没有扫描到，可以改成 `scanBasePackages = { "org.nebula.contrib.ngbatis", "com.ayi.ngbatis" }` 


> # Dao 类
> ![图片](https://user-images.githubusercontent.com/56581248/270079294-1aee4661-028c-41cc-ae4e-8812abebfb0c.png)

这里的`@Component`可以不需要，直接去掉就可以，扫描的发现是通过 xml 的 namespace 完成的，加了这个注解会形成二次代理，从而导致报错

**Comment by Childe-Mu** [comment]
按照上述方式修改，还是报错，追踪下来，看到是这个
![image](https://github.com/user-attachments/assets/b3bb910b-6bdc-4201-9f21-a3ab77a525ad)
bean没有被构建，还有其他需要修改的吗？
