### ISSUE TITLE
批量插入数据报错

### ISSUE THREAD

**Issue by AhYi8** [nebula-contrib/ngbatis#260]
一次性插入500条数据就开始报错了，请问这个是框架限制了吗？如何配置呢？
```
org.nebula.contrib.ngbatis.exception.QueryException: execute failed:  ResultSet error: SemanticError: The maximum number of statements allowed has been exceeded
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeBySessionPool(MapperProxy.java:290)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:133)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:169)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.pageSupport(MapperProxy.java:185)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:89)
	at ****************.dao.nebula.NebulaDao$Proxy.batchInsert********PersonAist(Unknown Source)
	at *****************.service.nebula.impl.NebulaServiceImpl.*******DataToNebula(NebulaServiceImpl.java:46)
	at ****************.schedule.****ImportSchedule.********Import1(HuaDanImportSchedule.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.nebula.contrib.ngbatis.exception.QueryException:  ResultSet error: SemanticError: The maximum number of statements allowed has been exceeded
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeBySessionPool(MapperProxy.java:287)
	... 20 more
```

**Comment by CorvusYe** [comment]
不是框架限制的，是 nebula 一次消息的最大长度 4194304，但是我忘记单位是什么了
