### ISSUE TITLE
selectById报错

### ISSUE THREAD

**Issue by llinzhe** [nebula-contrib/ngbatis#69]
# 错误日志：
	- proxyMethod: sun.reflect.NativeMethodAccessorImpl#invoke0 
	- nGql：
        match (n) where id(n) == $id return n
    
 
	 - params: {id=token001}
	 - result：null

org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败：java.lang.NullPointerException

	at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeWithParameter(MapperProxy.java:228)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:129)
	at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:87)
	at org.nebula.contrib.ngbatis.proxy.NebulaDaoBasic.selectById(NebulaDaoBasic.java:46)
	at TestNgbatis.test1(TestNgbatis.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

# 代码配置
- 启动类
```java
@ComponentScan(basePackages = {"org.nebula.contrib","cn.xxx"})
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}, scanBasePackages = {"org.nebula.contrib","cn.xxx"})
@EnableAsync
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);

    }
}
```
- mapper
```xml
<mapper
        namespace=
                "xxx.xx.xxx.EquipmentRepository" space="userProfile"
>
```

-

**Comment by CorvusYe** [comment]
`xml文件的 namespace` 与 `SpringBootApplication的 scanBasePackages` 帮忙确认下这两者的一致性哈，不确定会不会是这个问题导致的。

方便在`MapperProxy.executeWithParameter(MapperProxy.java:228)` 中断点看下 `e` 的异常栈吗

这边的报错提示不是很友好，后续会追加一个 Cause by。

**Comment by llinzhe** [comment]
> `xml文件的 namespace` 与 `SpringBootApplication的 scanBasePackages` 帮忙确认下这两者的一致性哈，不确定会不会是这个问题导致的。

**Comment by llinzhe** [comment]
xml文件的 namespace 与 SpringBootApplication的 scanBasePackages 帮忙确认下这两者的一致性哈，不确定会不会是这个问题导致的。

**Comment by llinzhe** [comment]
找到原因了，我修改了配置的读取，password没有注入，导致getSession的时候报了空指针

**Comment by CorvusYe** [comment]
那下午优化一下提示。感谢反馈
