### ISSUE TITLE
nebula服务session超时时间的值调小, 会发现Session not existed, 长时间得不到修正

### ISSUE THREAD

**Issue by soul-gin** [nebula-contrib/ngbatis#80]
#### 场景
如果把nebula服务session超时时间的值调小, 会发现Session not existed, 长时间得不到修正
--client_idle_timeout_secs=3600
--session_idle_timeout_secs=3600

#### 这里的参数是否可以通过配置设定?
public static long SESSION_LIFE_LENGTH = 5 * 60 * 60 * 1000;
public static long CHECK_FIXED_RATE = 5 * 60 * 60 * 1000;

#### 错误信息
2022-11-03 13:02:13.904 ERROR [ConsumeMessageThread_13] [] [com.kcbe.sme.kgraph.sync.service.rocketmq.RocketMqTaxConsumer:80] - GraphMqMsgConsumerTax upsert nebula, error:org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败： 数据查询失败Get sessionId[1667447161532634] failed: Session `1667447161532634' not found: Session not existed!
        at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeWithParameter(MapperProxy.java:228)

2022-11-03 14:27:51.503 ERROR [ConsumeMessageThread_14] [] [com.kcbe.sme.kgraph.sync.service.rocketmq.RocketMqApplyConsumer:88] - GraphMqMsgConsumerApply upsert nebula, error:org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败： 数据查询失败Get sessionId[1667447161532634] failed: Session `1667447161532634' not found: Session not existed!
        at org.nebula.contrib.ngbatis.proxy.MapperProxy.executeWithParameter(MapperProxy.java:228)
        at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:129)
        at org.nebula.contrib.ngbatis.proxy.MapperProxy.invoke(MapperProxy.java:87)
        at org.nebula.contrib.ngbatis.proxy.NebulaDaoBasic.upsertByIdSelective(NebulaDaoBasic.java:409)
        at com.kcbe.sme.kgraph.sync.service.nebula.impl.TagEnterpriseServiceImpl.upsertEntApply(TagEnterpriseServiceImpl.java:43)
        at com.kcbe.sme.kgraph.sync.service.rocketmq.RocketMqApplyConsumer.onMessage(RocketMqApplyConsumer.java:74)
        at com.kcbe.sme.kgraph.sync.service.rocketmq.RocketMqApplyConsumer.onMessage(RocketMqApplyConsumer.java:32)
        at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.handleMessage(DefaultRocketMQListenerContainer.java:394)
        at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:70)
        at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:354)
        at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:412)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by CorvusYe** [comment]
> public static long SESSION_LIFE_LENGTH = 5 * 60 * 60 * 1000;
public static long CHECK_FIXED_RATE = 5 * 60 * 60 * 1000;

目前这段是固定的，还不支持通过 yml 配置进行修改。

**Comment by CorvusYe** [comment]
但这个值是公开的常量，可以在项目启动的任意位置进行修改。

**Comment by soul-gin** [comment]
感谢, 没有留意到它们不是final

**Comment by CorvusYe** [comment]
需要注意的是 CHECK_FIXED_RATE 的赋值需要在 `org.nebula.contrib.ngbatis.session.IntervalCheckSessionDispatcher#wakeUp` 方法执行之前。
比如说使用**类的静态代码块**或者springboot `app.run(args)`之前进行赋值。
