### ISSUE TITLE
[1.1.1] org.springframework.beans.factory.NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by CorvusYe** [nebula-contrib/ngbatis#99]
```log
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.nebula.contrib.ngbatis.binding.Setter<?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 106 more
```

When this exception occurs in your project, please refer to the following steps:
Because the specific type of BigDecimal attribute in the project database cannot be determined, the project needs to be configured according to its own needs:
    1. Refer to [ValueType](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/annotations/ValueType.java) to create annotations that can distinguish entity attributes (or use existing annotations in your own project)
    2. Refer to [BigDecimalSetter](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/config/BigDecimalSetter.java) to configure different field types.
    3. [If BigDecimal is used] Place the annotation on the BigDecimal attribute of the java entity class, such as the height attribute in [Person](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Person.java).

----
当项目中出现此异常时，请参考以下步骤：
因为不能确定BigDecimal的属性在项目数据库中所对应的具体类型，项目中需要根据自身需要进行配置：
    1. 参考[ ValueType ](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/annotations/ValueType.java) 创建能为实体属性做类型区分的注解（或使用自身项目中已有注解）
    2. 参考[ BigDecimalSetter ](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/config/BigDecimalSetter.java)对不同的字段类型配置。
    3. 【如果项目中使用了BigDecimal】将注解放置到java实体类的BigDecimal属性上，如[ Person ](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Person.java)中的 height 属性。

**Comment by CorvusYe** [comment]
If your own project no exists BigDecimal: 
```java
@Component
public class VoidSetter implements Setter<Void> {

  @Override
  public Object set(Void param) {
    return void;
  }

}
